### ISSUE TITLE
Installation 

### ISSUE THREAD

**Issue by fcarvalhopacheco** [webbpinner/OpenVDMv2#26]
Hi Webb,

I tried again without success.  I followed your installation.md guide. The only difference is that I installed using a virtual box instead of digital ocean.

See what happen when I try to open the web application:

<img width="608" alt="Screen Shot 2020-12-15 at 13 26 57" src="https://user-images.githubusercontent.com/37884899/102284991-651a9b80-3ed9-11eb-8f65-cb87a6a64ec4.png">

Just for reference: under `/etc/apache2/sites-available`
```
<VirtualHost *:80>
    ServerName kilo-moana
....
```

**Comment by webbpinner** [comment]
Ok. So looks like something in the script failed.

**Comment by fcarvalhopacheco** [comment]
Is there any error log that I can access?

**Comment by webbpinner** [comment]
Sorry, hit send by mistake.   Can you send me the output from the installation script?  

You can run the script again if you need to. 

-W

**Comment by fcarvalhopacheco** [comment]
Interesting! 

First I saw the following errors which seemed to be related to git (` git: command not found`) 
```
#####################################################################
The directory '/home/fcp/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/fcp/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.


#####################################################################
Creating required directories
Making data directories starting at: /vault
#####################################################################
Configuring gearman-job-server
Restarting Gearman Job Server
#####################################################################
Configuring MySQL
Enabling MySQL Database Server
Synchronizing state of mysql.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable mysql
Setting up database root user and permissions
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
Database root password failed
Current database password for root? (if one exists - hit return if not) 
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
Setting up OpenVDM database user
mysql: [Warning] Using a password on the command line interface can be insecure.
Done setting up MySQL
#####################################################################
Configuring Supervisor
#####################################################################
Installing/Configuring OpenVDM
Downloading OpenVDMv2 repository.
/home/fcp/install-openvdm-ubuntu18.04.sh: line 570: git: command not found
chown: cannot access 'OpenVDMv2': No such file or directory
/home/fcp/install-openvdm-ubuntu18.04.sh: line 591: cd: /home/fcp/OpenVDMv2: No such file or directory
mysqlshow: [Warning] Using a password on the command line interface can be insecure.
OpenVDMv2 database found, skipping database setup
mysql: [Warning] Using a password on the command line interface can be insecure.
Building web-app
/home/fcp/install-openvdm-ubuntu18.04.sh: line 620: cd: ./var/www/OpenVDMv2: No such file or directory
Installing web-app
rsync: link_stat "/var/www/OpenVDMv2" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender=3.1.2]
cp: cannot stat '/var/www/OpenVDMv2/.htaccess.dist': No such file or directory
/home/fcp/install-openvdm-ubuntu18.04.sh: line 629: /var/www/OpenVDMv2/app/Core/Config.php: No such file or directory
sed: can't read /var/www/OpenVDMv2/app/Core/Config.php.dist: No such file or directory
touch: cannot touch '/var/www/OpenVDMv2/errorlog.html': No such file or directory
chmod: cannot access '/var/www/OpenVDMv2/errorlog.html': No such file or directory
chown: cannot access '/var/www/OpenVDMv2': No such file or directory
Installing configuration files
cp: cannot stat '/usr/local/etc/openvdm/datadashboard.yaml.dist': No such file or directory
cat: /usr/local/etc/openvdm/openvdm.yaml.dist: No such file or directory
Installing executables
Configuring Supervisor processes
rsync: link_stat "/etc/supervisor/conf.d/*" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender=3.1.2]
mv: cannot stat '/etc/supervisor/conf.d/OVDM_runCollectionSystemTransfer.conf.dist': No such file or directory
mv: cannot stat '/etc/supervisor/conf.d/OVDM_postCollectionSystemTransfer.conf.dist': No such file or directory
Restarting Supervisor
#####################################################################
```

Then I installed git and ran the installation again: 

```
sudo apt install git 
```

After  running the installation and opening kilo-moana/OpenVDMv2 I got the message `An error has been reported`, and the errors are:

Maybe just need some chmod permission change? 

```
Exception information:

Date: Dec 16, 2020 0:22AM

Message: SQLSTATE[HY000] [1045] Access denied for user 'fcp'@'localhost' (using password: YES)

Code: 1045

File: /var/www/OpenVDMv2/app/Helpers/Database.php

Line: 62
Stack trace:

#******** /var/www/OpenVDMv2/app/Helpers/Database.php(62): PDO->__construct('mysql:host=loca...', 'fcp', '********')
#1 /var/www/OpenVDMv2/app/Core/Model.php(33): Helpers\Database::get()
#2 /var/www/OpenVDMv2/app/Controllers/Api/Warehouse.php(3********): Core\Model->__construct()
#3 /var/www/OpenVDMv2/app/Core/Router.php(122): Controllers\Api\Warehouse->__construct(NULL)
#4 /var/www/OpenVDMv2/app/Core/Router.php(214): Core\Router::invokeObject('Controllers\\Api...')
#5 /var/www/OpenVDMv2/app/Core/routes.php(218): Core\Router::dispatch()
#6 /var/www/OpenVDMv2/index.php(8********): require('/var/www/OpenVD...')
#7 {main}

Exception information:

Date: Dec 16, 2020 0:22AM

Message: SQLSTATE[HY000] [1045] Access denied for user 'fcp'@'localhost' (using password: YES)

Code: 1045

File: /var/www/OpenVDMv2/app/Helpers/Database.php

Line: 62
Stack trace:

#******** /var/www/OpenVDMv2/app/Helpers/Database.php(62): PDO->__construct('mysql:host=loca...', 'fcp', '********')
#1 /var/www/OpenVDMv2/app/Core/Model.php(33): Helpers\Database::get()
#2 /var/www/OpenVDMv2/app/Controllers/Api/Warehouse.php(3********): Core\Model->__construct()
#3 /var/www/OpenVDMv2/app/Core/Router.php(122): Controllers\Api\Warehouse->__construct(NULL)
#4 /var/www/OpenVDMv2/app/Core/Router.php(214): Core\Router::invokeObject('Controllers\\Api...')
#5 /var/www/OpenVDMv2/app/Core/routes.php(218): Core\Router::dispatch()
#6 /var/www/OpenVDMv2/index.php(8********): require('/var/www/OpenVD...')
#7 {main}

Exception information:

Date: Dec 16, 2020 0:22AM

Message: SQLSTATE[HY000] [1045] Access denied for user 'fcp'@'localhost' (using password: YES)

Code: 1045

File: /var/www/OpenVDMv2/app/Helpers/Database.php

Line: 62
Stack trace:

#******** /var/www/OpenVDMv2/app/Helpers/Database.php(62): PDO->__construct('mysql:host=loca...', 'fcp', '********')
#1 /var/www/OpenVDMv2/app/Core/Model.php(33): Helpers\Database::get()
#2 /var/www/OpenVDMv2/app/Controllers/Api/Warehouse.php(3********): Core\Model->__construct()
#3 /var/www/OpenVDMv2/app/Core/Router.php(122): Controllers\Api\Warehouse->__construct(NULL)
#4 /var/www/OpenVDMv2/app/Core/Router.php(214): Core\Router::invokeObject('Controllers\\Api...')
#5 /var/www/OpenVDMv2/app/Core/routes.php(218): Core\Router::dispatch()
#6 /var/www/OpenVDMv2/index.php(8********): require('/var/www/OpenVD...')
#7 {main}

Exception information:

Date: Dec 16, 2020 0:22AM

Message: SQLSTATE[HY000] [1045] Access denied for user 'fcp'@'localhost' (using password: YES)

Code: 1045

File: /var/www/OpenVDMv2/app/Helpers/Database.php

Line: 62
Stack trace:

#******** /var/www/OpenVDMv2/app/Helpers/Database.php(62): PDO->__construct('mysql:host=loca...', 'fcp', '********')
#1 /var/www/OpenVDMv2/app/Core/Model.php(33): Helpers\Database::get()
#2 /var/www/OpenVDMv2/app/Controllers/Api/Tasks.php(19): Core\Model->__construct()
#3 /var/www/OpenVDMv2/app/Core/Router.php(122): Controllers\Api\Tasks->__construct(NULL)
#4 /var/www/OpenVDMv2/app/Core/Router.php(214): Core\Router::invokeObject('Controllers\\Api...')
#5 /var/www/OpenVDMv2/app/Core/routes.php(218): Core\Router::dispatch()
#6 /var/www/OpenVDMv2/index.php(8********): require('/var/www/OpenVD...')
#7 {main}

Exception information:

Date: Dec 16, 2020 0:22AM

Message: SQLSTATE[HY000] [1045] Access denied for user 'fcp'@'localhost' (using password: YES)

Code: 1045

File: /var/www/OpenVDMv2/app/Helpers/Database.php

Line: 62
Stack trace:

#******** /var/www/OpenVDMv2/app/Helpers/Database.php(62): PDO->__construct('mysql:host=loca...', 'fcp', '********')
#1 /var/www/OpenVDMv2/app/Core/Model.php(33): Helpers\Database::get()
#2 /var/www/OpenVDMv2/app/Controllers/Api/Warehouse.php(3********): Core\Model->__construct()
#3 /var/www/OpenVDMv2/app/Core/Router.php(122): Controllers\Api\Warehouse->__construct(NULL)
#4 /var/www/OpenVDMv2/app/Core/Router.php(214): Core\Router::invokeObject('Controllers\\Api...')
#5 /var/www/OpenVDMv2/app/Core/routes.php(218): Core\Router::dispatch()
#6 /var/www/OpenVDMv2/index.php(8********): require('/var/www/OpenVD...')
#7 {main}

Exception information:

Date: Dec 16, 2020 0:22AM

Message: SQLSTATE[HY000] [1045] Access denied for user 'fcp'@'localhost' (using password: YES)

Code: 1045

File: /var/www/OpenVDMv2/app/Helpers/Database.php

Line: 62
Stack trace:

#******** /var/www/OpenVDMv2/app/Helpers/Database.php(62): PDO->__construct('mysql:host=loca...', 'fcp', '********')
#1 /var/www/OpenVDMv2/app/Core/Model.php(33): Helpers\Database::get()
#2 /var/www/OpenVDMv2/app/Controllers/Api/Warehouse.php(3********): Core\Model->__construct()
#3 /var/www/OpenVDMv2/app/Core/Router.php(122): Controllers\Api\Warehouse->__construct(NULL)
#4 /var/www/OpenVDMv2/app/Core/Router.php(214): Core\Router::invokeObject('Controllers\\Api...')
#5 /var/www/OpenVDMv2/app/Core/routes.php(218): Core\Router::dispatch()
#6 /var/www/OpenVDMv2/index.php(8********): require('/var/www/OpenVD...')
#7 {main}

Exception information:

Date: Dec 16, 2020 0:22AM

Message: SQLSTATE[HY000] [1045] Access denied for user 'fcp'@'localhost' (using password: YES)

Code: 1045

File: /var/www/OpenVDMv2/app/Helpers/Database.php

Line: 62
Stack trace:

#******** /var/www/OpenVDMv2/app/Helpers/Database.php(62): PDO->__construct('mysql:host=loca...', 'fcp', '********')
#1 /var/www/OpenVDMv2/app/Core/Model.php(33): Helpers\Database::get()
#2 /var/www/OpenVDMv2/app/Controllers/Welcome.php(16): Core\Model->__construct()
#3 /var/www/OpenVDMv2/app/Core/Router.php(122): Controllers\Welcome->__construct(NULL)
#4 /var/www/OpenVDMv2/app/Core/Router.php(214): Core\Router::invokeObject('Controllers\\Wel...')
#5 /var/www/OpenVDMv2/app/Core/routes.php(218): Core\Router::dispatch()
#6 /var/www/OpenVDMv2/index.php(8********): require('/var/www/OpenVD...')
#7 {main}

Exception information:

Date: Dec 16, 2020 0:22AM

Message: SQLSTATE[HY000] [1045] Access denied for user 'fcp'@'localhost' (using password: YES)

Code: 1045

File: /var/www/OpenVDMv2/app/Helpers/Database.php

Line: 62
Stack trace:

#******** /var/www/OpenVDMv2/app/Helpers/Database.php(62): PDO->__construct('mysql:host=loca...', 'fcp', '********')
#1 /var/www/OpenVDMv2/app/Core/Model.php(33): Helpers\Database::get()
#2 /var/www/OpenVDMv2/app/Controllers/Welcome.php(16): Core\Model->__construct()
#3 /var/www/OpenVDMv2/app/Core/Router.php(122): Controllers\Welcome->__construct(NULL)
#4 /var/www/OpenVDMv2/app/Core/Router.php(214): Core\Router::invokeObject('Controllers\\Wel...')
#5 /var/www/OpenVDMv2/app/Core/routes.php(218): Core\Router::dispatch()
#6 /var/www/OpenVDMv2/index.php(8********): require('/var/www/OpenVD...')
#7 {main}

Exception information:

Date: Dec 16, 2020 0:23AM

Message: SQLSTATE[HY000] [1045] Access denied for user 'fcp'@'localhost' (using password: YES)

Code: 1045

File: /var/www/OpenVDMv2/app/Helpers/Database.php

Line: 62
Stack trace:

#******** /var/www/OpenVDMv2/app/Helpers/Database.php(62): PDO->__construct('mysql:host=loca...', 'fcp', '********')
#1 /var/www/OpenVDMv2/app/Core/Model.php(33): Helpers\Database::get()
#2 /var/www/OpenVDMv2/app/Controllers/Api/CollectionSystemTransfers.php(46): Core\Model->__construct()
#3 /var/www/OpenVDMv2/app/Core/Router.php(122): Controllers\Api\CollectionSystemTransfers->__construct(NULL)
#4 /var/www/OpenVDMv2/app/Core/Router.php(214): Core\Router::invokeObject('Controllers\\Api...')
#5 /var/www/OpenVDMv2/app/Core/routes.php(218): Core\Router::dispatch()
#6 /var/www/OpenVDMv2/index.php(8********): require('/var/www/OpenVD...')
#7 {main}
```

**Comment by webbpinner** [comment]
Just added an update to the install file that includes git.  This apparently is included by default with the digital ocean Ubuntu VM but is not part of the official install.

Looks like the OpenVDMv2 database was created but because the script could not download the OpenVDM source it did not have access to the database import script.  Thus all the required tables and initial fields are missing.

I'd recommend deleting the OpenVDMv2 database, re-downloading the updated OpenVDM install script and re-running the install script.

To delete the OpenVDMv2 database:
`mysql -u root -p`
`DROP DATABASE OpenVDMv2;`
`exit`

**Comment by fcarvalhopacheco** [comment]
Thanks Webb. 

I am reinstalling. Also just a heads up that I can't run the following:

```
$ ~/install-openvdm-ubuntu18.04.sh
ERROR: installation script must be run as root.

```
Instead, I ran 

```
$ sudo bash ~/install-openvdm-ubuntu18.04.sh
```

**Comment by webbpinner** [comment]
Should work fine.  The INSTALL.md suggests to login as root which would negate the need for sudo.  Either way should work.

**Comment by fcarvalhopacheco** [comment]
Good news!

<img width="608" alt="Screen Shot 2020-12-15 at 13 26 57" src="https://user-images.githubusercontent.com/37884899/102378696-2bde3c00-3f6a-11eb-843e-5591ccdb8c2b.png">

**Comment by fcarvalhopacheco** [comment]
Good news!

We have a loading day today and a cruise from 17th to 22nd. I will play around during the cruise.

<img width="1227" alt="Screen Shot 2020-12-16 at 06 44 30" src="https://user-images.githubusercontent.com/37884899/102378774-3ef10c00-3f6a-11eb-8c31-2edb5033db2f.png">

<img width="1522" alt="Screen Shot 2020-12-16 at 06 49 05" src="https://user-images.githubusercontent.com/37884899/102379291-d35b6e80-3f6a-11eb-81a3-0ac3c68fcd80.png">

**Comment by webbpinner** [comment]
That first update had me worried.  Can you please confirm the you can login user:"admin", pass:"demo"  Also don't forget to go the configuration-->system tab and set the IP address for this server in the "Edit Shipboard Data Warehouse" section.

[UPDATE] - Looks like the login worked

**Comment by fcarvalhopacheco** [comment]
Should I use the one from `hostname -I`?

**Comment by webbpinner** [comment]
Use the IP/hostname you plan to use when connecting to OpenVDM from the ship's network.

**Comment by fcarvalhopacheco** [comment]
Sounds good. I will keep you posted during the cruise. I am not on the ship right now
